[project]
name = "music-hub-review-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "fastapi[standard]>=0.138.0",
    "greenlet>=3.5.2",
    "pyjwt[crypto]>=2.13.0",
    "redis[hiredis]>=8.1.0",
    "sqlalchemy>=2.0.51",
    "tenacity>=9.1.4",
]

[dependency-groups]
dev = [
    "aiosqlite>=0.22.1",
]
