"""change review_id to id on the model

Revision ID: 1a34e2ef22cc
Revises: ac024ca1e28d
Create Date: 2026-10-01 17:19:55.107438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a34e2ef22cc'
down_revision: Union[str, Sequence[str], None] = 'ac024ca1e28d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Uuid(), nullable=False))
        batch_op.drop_column('review_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_id', sa.CHAR(length=32), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
